# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  - job: PreFlightCheck
    displayName: 'Pre-Flight Check'
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - checkout: self
      - bash: |
          set -euo pipefail
          echo "Build Source Branch: $(Build.SourceBranchName)"
          echo "core change"
          echo "##vso[task.setvariable variable=JOB_TRIGGER_CORE;isOutput=true]true"
          echo "geth change"
          echo "##vso[task.setvariable variable=JOB_TRIGGER_GETH_POA;isOutput=true]true"
          echo "ui change"
          echo "##vso[task.setvariable variable=JOB_TRIGGER_UI;isOutput=true]true"
          echo "sdk change"
          echo "##vso[task.setvariable variable=JOB_TRIGGER_SDK;isOutput=true]true"
        displayName: check git for changes
        name: setVars
      - bash: |
          echo "sourceBranch: " $(Build.sourceBranch)
          echo "SourceBranch: " $(Build.SourceBranch)
          echo "SourceBranchName: " $(Build.SourceBranchName)


  - job: job_2
    dependsOn:
    - PreFlightCheck
    condition: |
      and
      (
        eq(dependencies.PreFlightCheck.outputs['setVars.JOB_TRIGGER_GETH_POA'], 'true'),
        eq(dependencies.PreFlightCheck.outputs['setVars.JOB_TRIGGER_CORE'], 'true'),
        eq(dependencies.PreFlightCheck.outputs['setVars.JOB_TRIGGER_UI'], 'true'),
        eq(dependencies.PreFlightCheck.outputs['setVars.JOB_TRIGGER_SDK'], 'true')
      )
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - checkout: self
      - bash: |
          echo "now running job 2"

  - job: job_3
    dependsOn:
    - PreFlightCheck
    condition: |
      and
      (
        succeeded(),
          not(eq(variables['Build.SourceBranch'], 'refs/heads/master')),
          not(eq(variables['Build.SourceBranch'], 'refs/tags')),
        or
        (
          eq(dependencies.PreFlightCheck.outputs['setVars.JOB_TRIGGER_UI'], 'true'),
          eq(dependencies.PreFlightCheck.outputs['setVars.JOB_TRIGGER_SDK'], 'true')
        )
      )

    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - checkout: self
      - bash: |
          echo "now running job 3"
          echo "sourceBranch: " $(Build.sourceBranch)
          echo "SourceBranch: " $(Build.SourceBranch)
          echo "SourceBranchName: " $(Build.SourceBranchName)

